# Generated by Django 6.1.1 on 2026-09-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
