# Generated by Django 6.1.1 on 2026-09-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('short_description', models.TextField()),
                ('size', models.CharField(choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'Extra Large')], max_length=1)),
                ('weight', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
