# Generated by Django 6.1.1 on 2026-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
