# Generated by Django 6.1.1 on 2026-09-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'very good')], max_length=1),
        ),
    ]
